### ISSUE TITLE
error: Package ‘acm-0.1’ is unavailable

### ISSUE THREAD

**Issue by woshahua** [twlz0ne/acm-terminal#1]
got an error, when try to download the package from quelpa

`error: Package ‘acm-0.1’ is unavailable`

---
emacs version: 28.2

**Comment by twlz0ne** [comment]
Ah, my bad. 

It shouldn't be installed with `quelpa`, use `git clone /path/to/acm-terminal` instead.

See the commit https://github.com/twlz0ne/acm-terminal/commit/7d5c96780c566b3544a3a8f4b162dbe3d9d6bd46

**Comment by woshahua** [comment]
thx, it works perfect now!
