### ISSUE TITLE
noisy popon frame

### ISSUE THREAD

**Issue by GTrunSec** [twlz0ne/acm-terminal#7]
lsp-bridge: latest

this issue might be from  `acm-terminal-doc`.
Image:
![image](https://github.com/twlz0ne/acm-terminal/assets/21156405/efdcce9f-0949-4df5-9586-78708b0e9ee0)

**Comment by twlz0ne** [comment]
Can't reproduce.  Have you tested it in `emacs -Q`?

E.g.:

```elisp
$ emacsq.sh -nw --eval "\
  (progn
    ;; Install
    (unless (package-installed-p 'yasnippet)
      (package-install 'yasnippet))
    (add-to-list 'load-path \"~/repos/emacs-lsp-bridge\")
    (unless (display-graphic-p)
      (add-to-list 'load-path \"~/repos/emacs-popon\")
      (add-to-list 'load-path \"~/repos/emacs-acm-terminal\"))
    ;; Configure
    (require 'yasnippet)
    (yas-global-mode 1)
    (require 'lsp-bridge)
    (global-lsp-bridge-mode)
    (unless (display-graphic-p)
      (with-eval-after-load 'acm
        (require 'acm-terminal))))"
```

**Comment by bommbo** [comment]
> 无法重现。 你有没有测试过它 `emacs -Q`？
> 
> 例如：
> 
> ```emacs-lisp
> $ emacsq.sh -nw --eval "\
>   (progn
>     ;; Install
>     (unless (package-installed-p 'yasnippet)
>       (package-install 'yasnippet))
>     (add-to-list 'load-path \"~/repos/emacs-lsp-bridge\")
>     (unless (display-graphic-p)
>       (add-to-list 'load-path \"~/repos/emacs-popon\")
>       (add-to-list 'load-path \"~/repos/emacs-acm-terminal\"))
>     ;; Configure
>     (require 'yasnippet)
>     (yas-global-mode 1)
>     (require 'lsp-bridge)
>     (global-lsp-bridge-mode)
>     (unless (display-graphic-p)
>       (with-eval-after-load 'acm
>         (require 'acm-terminal))))"
> ```

same issue here. you can update lsp-bridge.

**Comment by twlz0ne** [comment]
@GTrunSec @bommbo Let me know if it works for you. If not, feel free to reopen this issue.

**Comment by GTrunSec** [comment]
@twlz0ne Thanks, fantastic work. No longer here!!!
