### ISSUE TITLE
希望在Daemon下运行可以手动切换terminal或者gui补全 或者自适应

### ISSUE THREAD

**Issue by yuzhou721** [twlz0ne/acm-terminal#9]
当前环境是在一台服务器上是用emacs，有时候是vnc连接上去开发，有时候是ssh登录上去开发，希望能自适应切换，因为acm-terminal在GUI环境下有对齐问题，目前我是手动把advice-add复制出来做了一个函数触发

**Comment by twlz0ne** [comment]
可以增加一对函数 `acm-terminal-[de]active`。

**Comment by twlz0ne** [comment]
@yuzhou721 看看最新提交是否有助于解决你的问题 https://github.com/twlz0ne/acm-terminal/commit/1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba

**Comment by yuzhou721** [comment]
谢谢大佬 测试了下 就是需要的效果
